disabled_rules: # rule identifiers to exclude from running
 - force_cast
 - force_try
 - syntactic_sugar

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods

function_body_length:
    warning: 200
    error: 500

variable_name:
    min_length: 1

type_name:
    max_length: 60 

identifier_name:
    max_length: 60